In [1]:
import numpy as np

In [9]:
array = np.arange(2, 50, 3)
array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [29]:
input1 = input()
input2 = input()
list1 = input1.split(' ')
list2 = input2.split(' ')
print(list1,list2)
print((list1+list2))
print(sorted(list1), sorted(list2)) 

1 2 3 4 5
9 8 7 6 5
['1', '2', '3', '4', '5'] ['9', '8', '7', '6', '5']
['1', '2', '3', '4', '5', '9', '8', '7', '6', '5']
['1', '2', '3', '4', '5'] ['5', '6', '7', '8', '9']


In [34]:
a = np.array(range(0,10))
print(a.shape)
print(a.size)

(10,)
10


In [79]:
a = np.array(range(0,10))
print(a[:, np.newaxis])
print(a[:, np.newaxis].shape)
##
print(a.reshape(2,5))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [53]:
a = [1,2,3,4,5]
b= [6,7,8,9,10]
print(np.hstack([a,b]))
a = [1,2,3,4,5]
b= [6,7,8,9,10]
print(np.vstack([a,b]))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [75]:
a = np.array([1,2,3]).repeat(3)
print(np.unique(a))
unique_values, count = np.unique(a, return_counts=True)
print(unique_values, count)

[1 2 3]
[1 2 3] [3 3 3]
